apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galerts.grafana.abarrak.com
spec:
  group: grafana.abarrak.com
  scope: Namespaced
  names:
    kind: GrafanaAlertRules
    listKind: GrafanaAlertRulesList
    plural: galerts
    singular: galert
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            rules:
              type: string
            ruleGroups:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  interval:
                    type: integer
